INSERT INTO PERSONAJES VALUES
	(NULL,'ALEXANDRA','METAHUMAN','F',13,'FUGITIVA NIVEL 6','MATERIALIZAR CUALQUIER COSA USANDO NANOBOTS','TURIN',null,NOW(),NOW(),NULL),
    (NULL, 'KARA ZYEN', 'ALIENÍGENA', 'F', 28, 'FUGITIVA NIVEL 7', 'CONTROL MENTAL Y TELEQUINESIS', 'VEGA-9', NULL, NOW(), NOW(), NULL),
	(NULL, 'DANIEL STRYKER', 'HUMANO ALTERADO', 'M', 35, 'VIGILANTE NIVEL 4', 'FUERZA SOBREHUMANA Y SENTIDOS AGUDIZADOS', 'NEOTOKYO', NULL, NOW(), NOW(), NULL),
	(NULL, 'LIRA NOVAK', 'INTELIGENCIA ARTIFICIAL', 'F', 3, 'AGENTE CLASIFICADO', 'INTERFAZ MENTAL CON TECNOLOGÍA', 'LABORATORIO X-7', NULL, NOW(), NOW(), NULL),
	(NULL, 'RAEL THORN', 'HÍBRIDO', 'M', 21, 'EXILIADO NIVEL 5', 'CONTROL SOBRE ELEMENTOS NATURALES', 'PLANICIE DE ASHUR', NULL, NOW(), NOW(), NULL),
	(NULL, 'NOVA SKYE', 'METAHUMAN', 'F', 18, 'REBELDE NIVEL 3', 'VELOCIDAD LUZ Y VIAJE TEMPORAL', 'SECTOR 12-B', NULL, NOW(), NOW(), NULL),
	(NULL, 'ORION VEX', 'CYBORG', 'M', 42, 'CAZADOR NIVEL 8', 'ARMA MULTIFUNCIÓN INCORPORADA', 'FÁBRICA 8 DEL DOMINIO', NULL, NOW(), NOW(), NULL);