CREATE DATABASE IF NOT EXISTS DBPRUEBA;
USE DBPRUEBA;

CREATE TABLE IF NOT EXISTS PERSONAJES(
	ID 			INT 			AUTO_INCREMENT PRIMARY KEY,
    NOMBRE 		VARCHAR(100) 	NOT NULL,
    ESPECIE 	VARCHAR(50)		NOT NULL,
    GENERO 		VARCHAR(20)		CHECK (GENERO IN ('M', 'F')),
    EDAD 		INT				NOT NULL,
    DESCRIPCION TEXT			NOT NULL,
    HABILIDADES TEXT,
    TERRITORIO 	VARCHAR(100),
    IMAGE_URL 	TEXT,
    created_at 	DATETIME,
    updated_at 	DATETIME,
    deleted_at 	DATETIME
)ENGINE=INNODB;